-- ============================================================
-- نظام ملائم العقاري — قاعدة البيانات على Supabase
-- 001_init: الجداول + الصلاحيات (RLS) + المشغّلات + تخزين الصور
-- الفكرة الأساسية: كل التحقق والصلاحيات هنا في السيرفر، وليس في المتصفح.
-- ============================================================

-- ---------- الجداول ----------

-- ملف الموظف: مربوط بحساب الدخول في auth.users
create table if not exists public.profiles (
    id          uuid primary key references auth.users (id) on delete cascade,
    legacy_id   integer generated by default as identity unique, -- الرقم الذي تراه الواجهة
    username    text not null unique,
    fullname    text,
    role        text not null check (role in ('admin', 'callcenter', 'field')),
    email       text,
    is_blocked  boolean not null default false,
    created_at  timestamptz not null default now()
);

-- موظفو النظام القديم (مرجع لإعادة إنشاء حساباتهم بنفس أسماء المستخدمين)
create table if not exists public.legacy_users (
    id          integer primary key,
    username    text not null unique,
    fullname    text,
    role        text,
    email       text,
    created_at  timestamp,
    is_blocked  boolean not null default false
);

create table if not exists public.projects (
    id                  integer generated by default as identity primary key,
    name                text not null,
    type                text,
    price               numeric(14,2),
    area                numeric(10,2),
    address             text,
    latitude            double precision,
    longitude           double precision,
    notes               text,
    employee            text,
    added_by            text,
    images              jsonb not null default '[]',
    image_files         jsonb not null default '[]',
    details             jsonb not null default '{}',
    status              text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
    date_added          timestamp default (now() at time zone 'Asia/Riyadh'),
    deletion_requested  boolean not null default false,
    rejection_reason    text,
    deleted_at          timestamp,
    availability        text not null default 'available'
);
create index if not exists projects_status_idx   on public.projects (status);
create index if not exists projects_type_idx     on public.projects (type);
create index if not exists projects_added_by_idx on public.projects (added_by);

create table if not exists public.activities (
    id          integer generated by default as identity primary key,
    user_id     integer,
    action      text,
    details     text,
    "timestamp" timestamp default (now() at time zone 'Asia/Riyadh'),
    user_name   text
);
create index if not exists activities_ts_idx on public.activities ("timestamp" desc);

-- الموقع الرئيسي mulaem.sa
create table if not exists public.site_projects (
    id                 integer generated by default as identity primary key,
    title              text,
    city               text,
    city_id            text,
    district           text,
    type               text,
    type_id            text,
    price              numeric(14,2),
    installment_price  numeric(14,2),
    area               numeric(10,2),
    rooms              integer,
    baths              integer,
    description        text,
    features           jsonb,
    gallery            jsonb,
    image              text,
    status             text,
    created_at         timestamp
);

create table if not exists public.site_settings (
    key    text primary key,
    value  text
);

-- ---------- دوال مساعدة (تقرأ هوية المستخدم من التوكن، والمعطَّل يُعامل كمجهول) ----------

create or replace function public.my_role() returns text
language sql stable security definer set search_path = public as
$$ select p.role from public.profiles p where p.id = auth.uid() and not p.is_blocked $$;

create or replace function public.my_username() returns text
language sql stable security definer set search_path = public as
$$ select p.username from public.profiles p where p.id = auth.uid() and not p.is_blocked $$;

create or replace function public.is_admin() returns boolean
language sql stable security definer set search_path = public as
$$ select coalesce(public.my_role() = 'admin', false) $$;

-- ---------- المشغّلات ----------

-- المشاريع: السيرفر هو من يحدد صاحب المشروع وحالته، وليس المتصفح
create or replace function public.projects_guard() returns trigger
language plpgsql security definer set search_path = public as
$$
declare
    v_role text;
    v_user text;
    v_full text;
begin
    if auth.uid() is null then
        return new; -- استيراد/صيانة من لوحة Supabase
    end if;

    select p.role, p.username, p.fullname into v_role, v_user, v_full
    from public.profiles p where p.id = auth.uid() and not p.is_blocked;

    if v_role is null then
        raise exception 'غير مصرح';
    end if;

    if tg_op = 'INSERT' then
        new.added_by         := v_user;
        new.employee         := coalesce(v_full, v_user);
        new.date_added       := now() at time zone 'Asia/Riyadh';
        new.rejection_reason := null;
        new.deleted_at       := null;
        new.status           := case when v_role = 'admin' then 'approved' else 'pending' end;
    else
        new.id         := old.id;
        new.added_by   := old.added_by;
        new.date_added := old.date_added;
        if v_role <> 'admin' then
            -- تعديل الموظف الميداني يعيد المشروع لانتظار موافقة المدير
            new.employee         := old.employee;
            new.status           := 'pending';
            new.rejection_reason := null;
        end if;
    end if;
    return new;
end
$$;

drop trigger if exists projects_guard on public.projects;
create trigger projects_guard before insert or update on public.projects
for each row execute function public.projects_guard();

-- سجل النشاط: الاسم والرقم يؤخذان من الحساب الفعلي
create or replace function public.activities_guard() returns trigger
language plpgsql security definer set search_path = public as
$$
begin
    if auth.uid() is null then
        return new;
    end if;
    select p.legacy_id, coalesce(p.fullname, p.username) into new.user_id, new.user_name
    from public.profiles p where p.id = auth.uid();
    new."timestamp" := now() at time zone 'Asia/Riyadh';
    return new;
end
$$;

drop trigger if exists activities_guard on public.activities;
create trigger activities_guard before insert on public.activities
for each row execute function public.activities_guard();

-- ---------- الصلاحيات (Row Level Security) ----------

alter table public.profiles      enable row level security;
alter table public.legacy_users  enable row level security;
alter table public.projects      enable row level security;
alter table public.activities    enable row level security;
alter table public.site_projects enable row level security;
alter table public.site_settings enable row level security;

revoke all on public.profiles, public.legacy_users, public.projects, public.activities from anon;
grant select, update                 on public.profiles     to authenticated;
grant select                         on public.legacy_users to authenticated;
grant select, insert, update, delete on public.projects     to authenticated;
grant select, insert                 on public.activities   to authenticated;
grant select on public.site_projects, public.site_settings to anon, authenticated;
grant insert, update, delete on public.site_projects, public.site_settings to authenticated;

-- profiles: كل موظف يرى ملفه، والمدير يرى الجميع ويعدّلهم. الإنشاء والحذف عبر دالة admin-users فقط.
drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles for select to authenticated
using (id = auth.uid() or public.is_admin());

drop policy if exists profiles_update_admin on public.profiles;
create policy profiles_update_admin on public.profiles for update to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists legacy_users_admin on public.legacy_users;
create policy legacy_users_admin on public.legacy_users for select to authenticated
using (public.is_admin());

-- projects
drop policy if exists projects_select on public.projects;
create policy projects_select on public.projects for select to authenticated
using (
    public.is_admin()
    or (public.my_role() = 'callcenter' and status = 'approved' and deleted_at is null)
    or (public.my_role() = 'field' and ((status = 'approved' and deleted_at is null) or added_by = public.my_username()))
);

drop policy if exists projects_insert on public.projects;
create policy projects_insert on public.projects for insert to authenticated
with check (public.my_role() in ('admin', 'field'));

drop policy if exists projects_update on public.projects;
create policy projects_update on public.projects for update to authenticated
using (public.is_admin() or (public.my_role() = 'field' and added_by = public.my_username()))
with check (public.is_admin() or (public.my_role() = 'field' and added_by = public.my_username()));

drop policy if exists projects_delete on public.projects;
create policy projects_delete on public.projects for delete to authenticated
using (public.is_admin() or (public.my_role() = 'field' and added_by = public.my_username() and status <> 'approved'));

-- activities: الكل يسجّل، والمدير فقط يقرأ
drop policy if exists activities_insert on public.activities;
create policy activities_insert on public.activities for insert to authenticated
with check (public.my_role() is not null);

drop policy if exists activities_select_admin on public.activities;
create policy activities_select_admin on public.activities for select to authenticated
using (public.is_admin());

-- الموقع الرئيسي: القراءة عامة، والتعديل للمدير
drop policy if exists site_projects_read on public.site_projects;
create policy site_projects_read on public.site_projects for select to anon, authenticated using (true);
drop policy if exists site_projects_admin on public.site_projects;
create policy site_projects_admin on public.site_projects for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists site_settings_read on public.site_settings;
create policy site_settings_read on public.site_settings for select to anon, authenticated using (true);
drop policy if exists site_settings_admin on public.site_settings;
create policy site_settings_admin on public.site_settings for all to authenticated
using (public.is_admin()) with check (public.is_admin());

-- ---------- تخزين الصور ----------
insert into storage.buckets (id, name, public)
values ('project-images', 'project-images', true)
on conflict (id) do nothing;

drop policy if exists project_images_upload on storage.objects;
create policy project_images_upload on storage.objects for insert to authenticated
with check (bucket_id = 'project-images' and public.my_role() in ('admin', 'field'));

drop policy if exists project_images_delete on storage.objects;
create policy project_images_delete on storage.objects for delete to authenticated
using (bucket_id = 'project-images' and public.is_admin());
