-- 022_agent_router — موجّه الجهد لوكيل الاستيراد (docs/TASK_ROUTER.md).
-- طُبّقت على المشروع الحي باسم agent_router.
--
-- ما يضيفه:
--   * agent_model_calls: سجل كل نداء نموذج (الطبقة، النموذج، المزوّد، التفكير، درجة الجهد وأسبابها،
--     الرموز، التكلفة، النتيجة وفئة الفشل). المدير يقرأ، والكتابة من مفتاح الخدمة وحده.
--   * agent_requests.effort_hint: «تفكير عميق» من الموظف ('deep')، و cost_usd: مجموع تكلفة الطلب.
--   * سقفان يوميان يعدّلهما المدير في crm_settings: الإنفاق بالدولار، وعدد التصعيدات
--     (المحاولات المصعّدة + الطلبات العميقة). الوظيفة تفحصهما قبل كل نداء.
--   * agent_daily_cap() (عدد الطلبات) يبقى كما هو.

-- ============================================================
-- (1) سجل النداءات
-- ============================================================
create table if not exists public.agent_model_calls (
    id                bigint generated by default as identity primary key,
    request_id        uuid not null references public.agent_requests(id) on delete cascade,
    attempt           int  not null check (attempt between 1 and 3),
    tier              text not null,
    model             text not null,
    provider          text,                        -- من ردّ OpenRouter: من خدم النداء فعلاً
    reasoning         text not null,               -- off | effort:high | max_tokens:8000
    escalated         boolean not null default false, -- يُحسب في سقف التصعيد
    effort_score      int,
    effort_reasons    text[] not null default '{}',
    prompt_tokens     int,
    completion_tokens int,
    reasoning_tokens  int,
    cost_usd          numeric(10,6),
    outcome           text not null check (outcome in ('ok', 'invalid', 'error')),
    failure_class     text check (failure_class in ('format', 'evidence', 'reasoning')),
    created_at        timestamptz not null default now()
);
create index if not exists agent_model_calls_request_idx on public.agent_model_calls (request_id, created_at);
create index if not exists agent_model_calls_day_idx     on public.agent_model_calls (created_at);

alter table public.agent_model_calls enable row level security;
revoke all on public.agent_model_calls from anon, authenticated;
grant select on public.agent_model_calls to authenticated;
drop policy if exists agent_model_calls_admin_read on public.agent_model_calls;
create policy agent_model_calls_admin_read on public.agent_model_calls
    for select to authenticated using (public.is_admin());
-- لا سياسة إدخال أو تعديل أو حذف: مفتاح الخدمة (وظيفة agent-run) يتجاوز RLS، والعميل لا يكتب.

-- ============================================================
-- (2) أعمدة الطلب
-- ============================================================
alter table public.agent_requests
    add column if not exists effort_hint text not null default 'auto' check (effort_hint in ('auto', 'deep')),
    add column if not exists cost_usd    numeric(10,6);

-- الحارس كما في 020، مع: التكلفة يكتبها الخادم وحده، و«تفكير عميق» يُختار عند الإنشاء
-- ويُعدَّل ما دام الطلب في الانتظار فقط.
create or replace function public.agent_requests_guard() returns trigger
language plpgsql security definer set search_path = public as $$
declare v_uid uuid := auth.uid(); v_role text; v_today int;
begin
    new.instruction := btrim(new.instruction);
    if new.instruction = '' then raise exception 'التعليمات مطلوبة'; end if;

    if tg_op = 'UPDATE' then
        new.updated_at   := now();
        new.created_at   := old.created_at;
        new.requested_by := old.requested_by;
        new.kind         := old.kind;
    end if;

    -- مفتاح الخدمة (وظيفة الاستخراج) أو صيانة من لوحة Supabase أو agent_pick_target
    if v_uid is null or coalesce(current_setting('mulaem.agent_pick', true), '') = 'on' then
        return new;
    end if;

    v_role := public.my_role();
    if v_role is null then raise exception 'غير مصرح'; end if;

    if tg_op = 'INSERT' then
        new.requested_by := v_uid;
        new.status       := 'queued';
        new.attempts     := 0;
        new.tokens_used  := null;
        new.cost_usd     := null;
        new.error_ar     := null;
        new.lease_until  := null;
        new.stage        := null;
        new.candidates   := '[]';
        new.target_id    := null;
        if v_role = 'callcenter' and new.kind <> 'client' then
            raise exception 'مركز الاتصال ينشئ طلبات العملاء فقط';
        end if;
        if new.kind = 'external' and not public.is_admin() then
            raise exception 'الاستيراد من مصدر خارجي للمدير فقط';
        end if;
        -- السقف اليومي بتوقيت الرياض، لكل مستخدم بمن فيهم المدير
        select count(*) into v_today from public.agent_requests r
        where r.requested_by = v_uid
          and r.created_at >= (date_trunc('day', now() at time zone 'Asia/Riyadh') at time zone 'Asia/Riyadh');
        if v_today >= public.agent_daily_cap() then
            raise exception 'بلغت الحد اليومي لطلبات المساعد (% طلباً)', public.agent_daily_cap();
        end if;
        return new;
    end if;

    -- حالة التنفيذ يكتبها الخادم؛ المستخدم لا يملك إلا الإلغاء
    new.attempts    := old.attempts;
    new.tokens_used := old.tokens_used;
    new.cost_usd    := old.cost_usd;
    new.lease_until := old.lease_until;
    new.stage       := old.stage;
    new.candidates  := old.candidates;
    new.target_id   := old.target_id;
    if new.status is distinct from old.status then
        if new.status <> 'cancelled' or old.status not in ('queued', 'running') then
            raise exception 'حالة الطلب يحددها الخادم';
        end if;
    end if;
    if new.status <> 'cancelled' then new.error_ar := old.error_ar; end if;
    if old.status <> 'queued' then
        new.instruction := old.instruction;
        new.title       := old.title;
        new.effort_hint := old.effort_hint;
    end if;
    return new;
end $$;
revoke execute on function public.agent_requests_guard() from public, anon, authenticated;

-- ============================================================
-- (3) السقفان اليوميان
-- ============================================================
insert into public.crm_settings (key, value) values
    ('agent_daily_usd_cap', '2'),
    ('agent_daily_escalations', '10')
on conflict (key) do nothing;

-- رقم من crm_settings: jsonb رقماً أو نصاً رقمياً، وإلا القيمة الافتراضية
create or replace function public.agent_setting_number(p_key text, p_default numeric) returns numeric
language sql stable security definer set search_path = public as $$
    select coalesce((
        select case
                   when jsonb_typeof(value) = 'number' then (value #>> '{}')::numeric
                   when jsonb_typeof(value) = 'string' and (value #>> '{}') ~ '^\s*\d+(\.\d+)?\s*$' then btrim(value #>> '{}')::numeric
               end
          from public.crm_settings where key = p_key
    ), p_default)
$$;
revoke execute on function public.agent_setting_number(text, numeric) from public, anon, authenticated;
grant  execute on function public.agent_setting_number(text, numeric) to service_role;

-- إنفاق اليوم (توقيت الرياض) وعدد التصعيدات، مع السقفين. تناديه الوظيفة قبل كل نداء.
create or replace function public.agent_router_budget() returns jsonb
language sql stable security definer set search_path = public as $$
    with day as (
        select (date_trunc('day', now() at time zone 'Asia/Riyadh') at time zone 'Asia/Riyadh') as start
    )
    select jsonb_build_object(
        'spent_usd',      coalesce((select sum(c.cost_usd) from public.agent_model_calls c, day where c.created_at >= day.start), 0),
        'escalations',    (select count(*) from public.agent_model_calls c, day where c.created_at >= day.start and c.escalated),
        'usd_cap',        public.agent_setting_number('agent_daily_usd_cap', 2),
        'escalation_cap', public.agent_setting_number('agent_daily_escalations', 10)
    )
$$;
revoke execute on function public.agent_router_budget() from public, anon, authenticated;
grant  execute on function public.agent_router_budget() to service_role;
