-- 026_wa_triage — فرز Jev لعروض واتساب قبل إرسالها للمساعد (docs/JEV.md).
--
-- ما يضيفه:
--   * wa_triage: حكم الفرز (send | review | skip) لكل نص كتلة ومجموعة أسئلة، مع أسبابه وإجابات Jev واحتمالاتها،
--     وتصحيح المالك للنية. المفتاح بصمة النص؛ لا يُحفظ نص الرسالة ولا المرسل ولا جوال. المدير يقرأ، والكتابة من
--     مفتاح الخدمة وحده (وظيفة wa-triage).
--   * wa_triage_calls: سطر لكل نداء للوظيفة، من الصفحة أو من أداة التقييم: العناصر ونداءات Jev والرموز والتكلفة.
--   * wa_triage_tickets: تذاكر أداة التقييم (بصمة السر، سقف عناصر، تاريخ انتهاء). لا يصلها إلا مفتاح الخدمة.
--   * wa_triage_take_ticket: يحجز عناصر النداء من تذكرة في UPDATE واحد.
--   * wa_triage_budget: إنفاق الفرز اليوم بتوقيت الرياض مع سقفه. لا تناديه إلا الوظيفة.
--   * wa_triage_report: ملخص للمدير لكل مجموعة أسئلة: الأحكام وما أُرسل منها للمساعد، وشرائح ثقة النية،
--     وتصحيحات المالك، وتصنيف المحلّل × الحكم، والتكلفة.
--   * إعدادان في crm_settings: wa_triage_daily_usd_cap = 0.5 دولار، و wa_triage_mode = "suggest".
--
-- Jev يقترح فقط: لا يكتب في agent_requests ولا agent_drafts ولا projects ولا clients، ولا يصل شيء إلى المساعد إلا
-- حين يضغط المالك «إرسال للمساعد». agent_router_budget() لا يتغير: سقف المساعد (agent_daily_usd_cap) لا يشمل
-- الفرز، وللفرز سقفه المستقل.

-- ============================================================
-- (1) أحكام الفرز
-- ============================================================
-- صف لكل (نص، مجموعة أسئلة). المفتاح sha256 (hex) لنص الكتلة الأصلي بعد trim، يحسبه الخادم: النص نفسه في تصدير
-- جديد أو في مجموعة أخرى يجد حكمه بلا نداء، وتغيير الأسئلة (qset جديد) يعني حكماً جديداً.
-- source_shas: بصمات «نص المصدر» لنسخ الكتلة كما تحسبها الصفحة (المجموعة والمرسل ووقت النشر ثم النص)، وهي نفسها
-- agent_sources.sha256 حين تُرسل النسخة للمساعد؛ بها يعرف التقرير ما أُرسل.
-- answers: intent و city باحتمالاتهما كاملة، و kind و district بأعلى ثلاثة [[المفتاح، الاحتمال]، …]، و multiple {noul}.
-- owner_label: النية الصحيحة في رأي المالك (أحد مفاتيح intent الستة)، مع وقتها وصاحبها.
create table if not exists public.wa_triage (
    key            text not null,                 -- sha256 hex لنص الكتلة بعد trim
    qset           text not null,                 -- مجموعة الأسئلة: wa-1 …
    model          text not null,                 -- كما ردّه OpenRouter، أو ما تكتبه الوظيفة لحكم الكود بلا نداء
    verdict        text not null check (verdict in ('send', 'review', 'skip')),
    reasons        text[] not null default '{}',
    answers        jsonb not null,
    regex_kind     text,                          -- تصنيف المحلّل في الصفحة: offer | update | wanted | other | document
    source_shas    text[] not null default '{}',
    input_tokens   int,
    cost_usd       numeric(10,6),
    owner_label    text check (owner_label in ('sale_offer', 'rent_offer', 'status_update', 'wanted', 'not_property', 'other')),
    owner_label_at timestamptz,
    owner_label_by uuid references public.profiles(id),
    created_by     uuid references public.profiles(id),
    created_at     timestamptz not null default now(),
    updated_at     timestamptz not null default now(),
    primary key (key, qset)
);
create index if not exists wa_triage_created_idx     on public.wa_triage (created_at);
create index if not exists wa_triage_source_shas_idx on public.wa_triage using gin (source_shas);

alter table public.wa_triage enable row level security;
revoke all on public.wa_triage from anon, authenticated;
grant select on public.wa_triage to authenticated;
drop policy if exists wa_triage_admin_read on public.wa_triage;
create policy wa_triage_admin_read on public.wa_triage
    for select to authenticated using (public.is_admin());
-- لا سياسة إدخال أو تعديل أو حذف: مفتاح الخدمة (وظيفة wa-triage) يتجاوز RLS، وتصحيح المالك يمرّ بإجراء label فيها.

-- ============================================================
-- (2) سجل النداءات
-- ============================================================
-- سطر واحد لكل نداء للوظيفة (حتى 25 عنصراً)، من الصفحة أو من أداة التقييم، ومنه يُحسب إنفاق اليوم.
-- requested_by فارغ لنداء التقييم: التذكرة لا تحمل مستخدماً.
create table if not exists public.wa_triage_calls (
    id           bigint generated by default as identity primary key,
    purpose      text not null check (purpose in ('page', 'eval')),
    requested_by uuid references public.profiles(id),
    model        text,                          -- كما ردّه OpenRouter؛ فارغ إن لم يُنادَ Jev
    provider     text,
    items        int  not null,
    jev_calls    int  not null,
    cached       int  not null,
    errors       int  not null,
    input_tokens int,
    cost_usd     numeric(10,6),
    duration_ms  int,
    error        text,                          -- الجوالات والبريد مُخفاة، ولا مفتاح ولا نص SQL
    created_at   timestamptz not null default now()
);
create index if not exists wa_triage_calls_day_idx on public.wa_triage_calls (created_at);

alter table public.wa_triage_calls enable row level security;
revoke all on public.wa_triage_calls from anon, authenticated;
grant select on public.wa_triage_calls to authenticated;
drop policy if exists wa_triage_calls_admin_read on public.wa_triage_calls;
create policy wa_triage_calls_admin_read on public.wa_triage_calls
    for select to authenticated using (public.is_admin());
-- لا سياسة كتابة: مفتاح الخدمة وحده يكتب.

-- ============================================================
-- (3) تذاكر التقييم (service_role فقط)
-- ============================================================
-- أداة التقييم (scripts/jev-eval) تنادي الوظيفة المنشورة بلا جلسة مدير: ترسل السر في الترويسة x-triage-ticket،
-- فتحسب الوظيفة sha256 له وتحجز به عناصر النداء. نداء التذكرة لا يقرأ ذاكرة الفرز ولا يكتبها.
-- القاعدة تحفظ البصمة لا السر. تُنشأ التذكرة يدوياً، والبصمة تُحسب خارج القاعدة فلا يمرّ السر بلوحة SQL ولا بسجلها:
--   insert into public.wa_triage_tickets (token_hash, note, max_items, expires_at)
--   values ('<sha256 hex للسر>', 'تقييم wa-1', 600, now() + interval '2 days');
create table if not exists public.wa_triage_tickets (
    id         bigint generated by default as identity primary key,
    token_hash text not null unique,              -- sha256 hex للسر
    note       text,
    max_items  int  not null,
    used_items int  not null default 0,
    expires_at timestamptz not null,
    created_at timestamptz not null default now()
);
alter table public.wa_triage_tickets enable row level security;
revoke all on public.wa_triage_tickets from anon, authenticated;
-- لا سياسة أصلاً: لا يقرؤها ولا يكتبها إلا مفتاح الخدمة (ولوحة Supabase).

-- يحجز p_items عنصراً: الشرط والزيادة عبارة واحدة. نداءان متزامنان بالتذكرة نفسها: الثاني ينتظر قفل الصف، ثم يعيد
-- Postgres تقييم شرطه على الصف كما تركه الأول (Read Committed)، فلا يتجاوز المحجوز سقف التذكرة أبداً.
-- العدد السالب يُرفض قبل أي كتابة (وإلا أعاد إلى التذكرة عناصر)، والصفر يتحقق من صلاحية التذكرة ولا يحجز منها
-- شيئاً. الرفض رمز واحد أياً كان سببه (لا تذكرة، أو انتهت، أو لا يكفي ما بقي)، فلا يعرف المنادي أي البصمات موجودة.
create or replace function public.wa_triage_take_ticket(p_hash text, p_items int) returns jsonb
language plpgsql security definer set search_path = public as $$
declare v_remaining int;
begin
    if p_hash is null or p_items is null or p_items < 0 then
        return jsonb_build_object('ok', false, 'code', 'ticket_invalid');
    end if;
    update public.wa_triage_tickets t
       set used_items = t.used_items + p_items
     where t.token_hash = p_hash
       and t.expires_at > now()
       and p_items <= t.max_items - t.used_items        -- أي used_items + p_items <= max_items، بلا فيضان int
    returning t.max_items - t.used_items into v_remaining;
    if not found then
        return jsonb_build_object('ok', false, 'code', 'ticket_invalid');
    end if;
    return jsonb_build_object('ok', true, 'remaining', v_remaining);
end $$;
revoke execute on function public.wa_triage_take_ticket(text, int) from public, anon, authenticated;
grant  execute on function public.wa_triage_take_ticket(text, int) to service_role;

-- ============================================================
-- (4) الإعدادان وسقف الإنفاق اليومي
-- ============================================================
-- wa_triage_mode: off (لا فرز) | suggest (شارة الحكم والتصفية به فقط) | preselect (تُعلَّم العروض المؤكَّدة مسبقاً،
-- ويبقى الإرسال بضغطة المالك). غياب الصف يعني suggest. يغيّر المدير الوضع من صفحة «عروض واتساب»، أما السقف فلا
-- حقل له في أي صفحة: يُغيَّر بـ SQL أو من لوحة Supabase (سياسات crm_settings في 004 تسمح للمدير بكتابتهما).
insert into public.crm_settings (key, value) values
    ('wa_triage_daily_usd_cap', '0.5'),
    ('wa_triage_mode', '"suggest"')
on conflict (key) do nothing;

-- إنفاق الفرز اليوم (توقيت الرياض) مع سقفه. تناديه الوظيفة قبل فرز الصفحة، والسقف يوقف الصفحة وحدها: نداء التقييم
-- يُحسب في الإنفاق (السقف سقف مال) لكنه لا يُمنع به، فلتذكرته سقف عناصرها.
create or replace function public.wa_triage_budget() returns jsonb
language sql stable security definer set search_path = public as $$
    with day as (
        select (date_trunc('day', now() at time zone 'Asia/Riyadh') at time zone 'Asia/Riyadh') as start
    )
    select jsonb_build_object(
        'spent_usd', coalesce((select sum(c.cost_usd) from public.wa_triage_calls c, day where c.created_at >= day.start), 0),
        'cap_usd',   public.agent_setting_number('wa_triage_daily_usd_cap', 0.5)
    )
$$;
revoke execute on function public.wa_triage_budget() from public, anon, authenticated;
grant  execute on function public.wa_triage_budget() to service_role;

-- ============================================================
-- (5) تقرير المدير
-- ============================================================
-- ملخص لكل مجموعة أسئلة على صفوف النافذة: created_at >= now() - p_days يوماً (1..3650، الافتراضي 30).
--   * «أُرسل»: إحدى بصمات source_shas للصف موجودة في agent_sources.sha256 لطلب حالته ليست failed ولا cancelled،
--     وهو تعريف الصفحة نفسه لما أُرسل سابقاً. الربط مجموعيّ: تُفرد البصمات (unnest) وتُربط مرة واحدة بالتجزئة،
--     فلا استعلام لكل صف، و agent_sources (بلا فهرس على sha256) يُقرأ مرة واحدة.
--   * ثقة النية: answers->intent->confidence، وإن غابت فمن answers->intent->probabilities بالصيغة
--     (n·pmax − 1)/(n − 1)، وإن غابتا فهي منخفضة (شريحة <0.5). الصف بلا نية (حكم الكود: مستند فقط) خارج الشرائح
--     وداخل ما سواها.
--   * التصحيحات: count صفوف فيها owner_label، و agree ما وافق فيه owner_label نية Jev (answers->intent->>'choice').
--   * التكلفة من wa_triage_calls (الصفحة والتقييم معاً): اليوم بتوقيت الرياض، والنافذة كلها.
-- الشكل:
--   { "ok": true, "days": 30, "since": "<بداية النافذة>",
--     "cost":  { "today_usd": 0.0021, "window_usd": 0.015, "today_jev_calls": 50, "window_jev_calls": 357 },
--     "qsets": { "wa-1": {
--         "total": 309, "sent": 12,
--         "verdicts":    { "send":   { "count": 40,  "sent": 10 },
--                          "review": { "count": 100, "sent": 2 },
--                          "skip":   { "count": 169, "sent": 0 } },
--         "confidence":  [ { "band": ">=0.9",    "count": 150, "sent": 9 },
--                          { "band": "0.75-0.9", "count": 60,  "sent": 2 },
--                          { "band": "0.5-0.75", "count": 40,  "sent": 1 },
--                          { "band": "<0.5",     "count": 30,  "sent": 0 } ],
--         "corrections": { "count": 12, "agree": 9 },
--         "regex_kind":  { "offer": { "send": { "count": 30, "sent": 9 }, "review": {…}, "skip": {…} },
--                          "other": {…}, … } } } }
--   الأحكام الثلاثة والشرائح الأربع حاضرة دائماً ولو بأصفار، و regex_kind بما ظهر منه فقط (الفارغ باسم "none").
--   الشرائح مصفوفة لا كائن لأن jsonb لا يحفظ ترتيب المفاتيح: ≥0.9، ثم [0.75، 0.9)، ثم [0.5، 0.75)، ثم <0.5.
--   الرفض: { "ok": false, "code": "forbidden" } لغير المدير، و { "ok": false, "code": "invalid_days" }.
create or replace function public.wa_triage_report(p_days int default 30) returns jsonb
language plpgsql stable security definer set search_path = public as $$
declare
    v_since timestamptz;
    v_day   timestamptz := date_trunc('day', now() at time zone 'Asia/Riyadh') at time zone 'Asia/Riyadh';
    v_out   jsonb;
begin
    if not public.is_admin() then
        return jsonb_build_object('ok', false, 'code', 'forbidden');
    end if;
    if p_days is null or p_days < 1 or p_days > 3650 then
        return jsonb_build_object('ok', false, 'code', 'invalid_days');
    end if;
    v_since := now() - make_interval(days => p_days);

    with win as materialized (
        select t.key, t.qset, t.verdict, t.source_shas, t.owner_label,
               coalesce(nullif(t.regex_kind, ''), 'none') as regex_kind,
               t.answers->'intent'->>'choice' as intent,
               coalesce(
                   case when jsonb_typeof(t.answers->'intent'->'confidence') = 'number'
                        then (t.answers->'intent'->>'confidence')::numeric end,
                   (select (count(*) * max((p.value #>> '{}')::numeric) - 1) / nullif(count(*) - 1, 0)
                      from jsonb_each(case when jsonb_typeof(t.answers->'intent'->'probabilities') = 'object'
                                           then t.answers->'intent'->'probabilities' else '{}'::jsonb end) p
                     where jsonb_typeof(p.value) = 'number')
               ) as conf
          from public.wa_triage t
         where t.created_at >= v_since
    ),
    sent_rows as (
        select distinct w.key, w.qset
          from win w
          cross join lateral unnest(w.source_shas) as x(sha)
          join public.agent_sources  s on s.sha256 = x.sha
          join public.agent_requests r on r.id = s.request_id
         where r.status not in ('failed', 'cancelled')
    ),
    scored as materialized (
        select w.qset, w.verdict, w.regex_kind, w.owner_label, w.intent,
               (sr.key is not null) as is_sent,
               case when w.intent is null then null
                    when w.conf >= 0.9  then '>=0.9'
                    when w.conf >= 0.75 then '0.75-0.9'
                    when w.conf >= 0.5  then '0.5-0.75'
                    else '<0.5'
               end as band
          from win w
          left join sent_rows sr on sr.key = w.key and sr.qset = w.qset
    ),
    by_qset as (
        select s.qset,
               count(*)                                          as total,
               count(*) filter (where s.is_sent)                 as sent,
               count(*) filter (where s.owner_label is not null) as corrections,
               count(*) filter (where s.owner_label = s.intent)  as agree
          from scored s
         group by s.qset
    ),
    by_verdict as (
        select q.qset,
               jsonb_object_agg(v.verdict, jsonb_build_object('count', coalesce(g.n, 0), 'sent', coalesce(g.sent, 0))) as j
          from by_qset q
          cross join (values ('send'), ('review'), ('skip')) as v(verdict)
          left join (select s.qset, s.verdict, count(*) as n, count(*) filter (where s.is_sent) as sent
                       from scored s group by s.qset, s.verdict) g
                 on g.qset = q.qset and g.verdict = v.verdict
         group by q.qset
    ),
    by_band as (
        select q.qset,
               jsonb_agg(jsonb_build_object('band', b.band, 'count', coalesce(g.n, 0), 'sent', coalesce(g.sent, 0))
                         order by b.ord) as j
          from by_qset q
          cross join (values (1, '>=0.9'), (2, '0.75-0.9'), (3, '0.5-0.75'), (4, '<0.5')) as b(ord, band)
          left join (select s.qset, s.band, count(*) as n, count(*) filter (where s.is_sent) as sent
                       from scored s where s.band is not null group by s.qset, s.band) g
                 on g.qset = q.qset and g.band = b.band
         group by q.qset
    ),
    by_kind_verdict as (
        select k.qset, k.regex_kind,
               jsonb_object_agg(v.verdict, jsonb_build_object('count', coalesce(g.n, 0), 'sent', coalesce(g.sent, 0))) as j
          from (select distinct s.qset, s.regex_kind from scored s) k
          cross join (values ('send'), ('review'), ('skip')) as v(verdict)
          left join (select s.qset, s.regex_kind, s.verdict, count(*) as n, count(*) filter (where s.is_sent) as sent
                       from scored s group by s.qset, s.regex_kind, s.verdict) g
                 on g.qset = k.qset and g.regex_kind = k.regex_kind and g.verdict = v.verdict
         group by k.qset, k.regex_kind
    ),
    by_kind as (
        select kv.qset, jsonb_object_agg(kv.regex_kind, kv.j) as j
          from by_kind_verdict kv
         group by kv.qset
    )
    select jsonb_build_object(
        'ok',    true,
        'days',  p_days,
        'since', v_since,
        'cost',  (select jsonb_build_object(
                      'today_usd',        coalesce(sum(c.cost_usd) filter (where c.created_at >= v_day), 0),
                      'window_usd',       coalesce(sum(c.cost_usd), 0),
                      'today_jev_calls',  coalesce(sum(c.jev_calls) filter (where c.created_at >= v_day), 0),
                      'window_jev_calls', coalesce(sum(c.jev_calls), 0))
                    from public.wa_triage_calls c
                   where c.created_at >= v_since),
        'qsets', coalesce((
                     select jsonb_object_agg(q.qset, jsonb_build_object(
                                'total',       q.total,
                                'sent',        q.sent,
                                'verdicts',    v.j,
                                'confidence',  b.j,
                                'corrections', jsonb_build_object('count', q.corrections, 'agree', q.agree),
                                'regex_kind',  k.j))
                       from by_qset q
                       join by_verdict v on v.qset = q.qset
                       join by_band    b on b.qset = q.qset
                       join by_kind    k on k.qset = q.qset), '{}'::jsonb)
    ) into v_out;
    return v_out;
end $$;
revoke execute on function public.wa_triage_report(int) from public, anon;
grant  execute on function public.wa_triage_report(int) to authenticated;
